# Current Account Rules
min.balance=25000.0
interest.rate=0.0
daily.transfer.limit.new=100000.0
daily.transfer.limit.standard=250000.0
daily.transfer.limit.premium=500000.0
daily.transfer.limit.privilege=1000000.0
