# Savings Account Rules
min.balance=10000.0
interest.rate=4.0
daily.transfer.limit.new=50000.0
daily.transfer.limit.standard=100000.0
daily.transfer.limit.premium=200000.0
daily.transfer.limit.privilege=500000.0
