min.balance.new=10000
min.balance.standard=7500
min.balance.premium=5000
min.balance.privilege=2500

interest.rate.new=2.70
interest.rate.standard=3.00
interest.rate.premium=3.50
interest.rate.privilege=4.00

daily.limit.new=25000
daily.limit.standard=50000
daily.limit.premium=100000
daily.limit.privilege=200000
