# Salary Account Rules
min.balance=0.0
interest.rate=3.5
daily.transfer.limit.new=75000.0
daily.transfer.limit.standard=150000.0
daily.transfer.limit.premium=300000.0
daily.transfer.limit.privilege=750000.0
